Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24


In [6]:
import numpy as np

In [27]:
C=50
H=30
counter = 1
my_list=list()
my_inp=input(f'Enter the comma seperated sequence:')
print(my_inp)
my_inp=my_inp.split(',')
my_inp
for values in my_inp:
    D=int(values)
    result=np.sqrt((2*C*D)/H)
    my_list.append(int(round(result)))
print(my_list)

Enter the comma seperated sequence:100,150,180
100,150,180
[18, 22, 24]


Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡¬Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 


In [32]:
base_mat=np.ones((3,5))
base_mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
for rows in range(3):
    for columns in range(5):
        base_mat[rows][columns]=int(round(rows*columns))
print(base_mat)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world


In [40]:
inp_of_words=input('Provide the words that should be sorted with comma seperation:')

Provide the words that should be sorted with comma seperation:without,hello,bag,world


In [48]:
print(inp_of_words)

without,hello,bag,world


In [53]:
sorted_words=sorted(inp_of_words.split(','))

In [65]:
','.join(sorted_words)

'bag,hello,without,world'

Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world


In [47]:
input_str = input("Enter a sequence of words separated by space: ")

# Split the input string into a list of words
words = input_str.split()

# Remove the repeated words
unique_words = list(set(words))

# Sort the unique words in alphabetical order
unique_words.sort()

# Display the output
print("Unique words in alphabetical order:", *unique_words)


Enter a sequence of words separated by space: hello world and practice makes perfect and hello world again
Unique words in alphabetical order: again and hello makes perfect practice world


Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3
`

In [66]:
sentence = input("Enter a sentence: ")
letters = 0
digits = 0

for char in sentence:
    if char.isalpha():
        letters += 1
    elif char.isdigit():
        digits += 1

print("Number of letters:", letters)
print("Number of digits:", digits)


Enter a sentence: hello world! 123
Number of letters: 10
Number of digits: 3


Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1


In [67]:
import re

def check_password(password):
    if 6 <= len(password) <= 12:
        if re.search("[a-z]", password) and re.search("[0-9]", password) and re.search("[A-Z]", password) and re.search("[$#@]", password):
            return True
    return False

passwords = input("Enter comma separated passwords: ")
valid_passwords = []
for password in passwords.split(","):
    if check_password(password):
        valid_passwords.append(password)
print(",".join(valid_passwords))


Enter comma separated passwords: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
