1.	Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np

In [41]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,10,11])

In [42]:
arr3=np.zeros(arr1.shape)
for items in range(len(arr1)):
    arr3[items]=arr1[items]+arr2[items]
print(arr3)

[ 8. 10. 12. 14. 16.]


2.	Write a Python Program to Multiply Two Matrices?

In [48]:
arr4 = np.array([[1, 2], [3, 4]])
arr5= np.array([[5, 6], [7, 8]])
print(arr4)
print(arr5)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [49]:
arr6 = np.zeros(arr4.shape)
arr6

array([[0., 0.],
       [0., 0.]])

In [51]:
for i in range(len(arr4)):
    # Iterate over the columns of B
    for j in range(len(arr5[0])):
        # Iterate over the rows of B
        for k in range(len(arr5)):
            # Multiply and accumulate the products
            arr6[i][j] += arr4[i][k] * arr5[k][j]

In [52]:
arr6

array([[ 38.,  44.],
       [ 86., 100.]])

3.	Write a Python Program to Transpose a Matrix?

In [68]:
arr7=np.array([[1,2],[4,5],[8,9]])
arr7

array([[1, 2],
       [4, 5],
       [8, 9]])

In [80]:
print(arr7.transpose())

[[1 4 8]
 [2 5 9]]


In [103]:
arr8 = np.array([[0 for j in range(len(arr7))] for i in range(len(arr7[0]))])

In [104]:
arr8

array([[0, 0, 0],
       [0, 0, 0]])

In [105]:
for i in range(len(arr7)):
    for j in range(len(arr7[0])):
        arr8[j][i] = arr7[i][j]

print(arr8)
print(arr8.shape)

[[1 4 8]
 [2 5 9]]
(2, 3)


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [114]:
words_to_be_sorted=['Saravanesh','Saissh','Prathap']

In [120]:
sorted_words=list()
for words in words_to_be_sorted:
    sorted_word=''.join(sorted(words.lower()))
    sorted_words.append(sorted_word)

In [121]:
print(sorted_words)

['aaaehnrssv', 'ahisss', 'aahpprt']


5.	Write a Python Program to Remove Punctuation From a String?

In [122]:
import re

In [127]:
sample_string = "Hello! H#$#$ow are yo%$u doing& today?"

In [128]:
re.sub(r'[^\w\s]', '', sample_string)

'Hello How are you doing today'