1.	Write a Python Program to find sum of array?

In [4]:
#method 1
arr = [1,2,3,4,5]
print('The elements in array :',arr)
sum_ = 0
for items in arr:
    sum_ = sum_ + items
print('Sum of elements in array :',sum_)

The elements in array : [1, 2, 3, 4, 5]
Sum of elements in array : 15


In [3]:
#method 2 - Using sum function 
arr = [1,2,3,4,5]
print('Elements in array :',arr)
print('Sum of elements of array :', sum(arr))

Elements in array : [1, 2, 3, 4, 5]
Sum of elements of array : 15


In [5]:
#method 3 using numpy array
import numpy as np
arr1 = np.array([1,2,3,4,5])
print('Elements in array :',arr1)
print('Sum of elements in array :',np.sum(arr1))

Elements in array : [1 2 3 4 5]
Sum of elements in array : 15


2.	Write a Python Program to find largest element in an array?

In [7]:
print('The array elements :',arr)
max_num = 0
for elements in arr:
    if elements > max_num:
        max_num = elements
print('Maximum element in the array :', max_num)

The array elements : [1, 2, 3, 4, 5]
Maximum element in the array : 5


In [8]:
#Method - 2, using the max function
max(arr)

5

3.	Write a Python Program for array rotation?

In [1]:
def rotate_array(arr, k):
    n = len(arr)
    k = k % n  # Adjust k if it is larger than n
    return arr[-k:] + arr[:-k]


In [2]:
rotate_array([2,3,4,5,6,3],1)

[3, 2, 3, 4, 5, 6]

In [3]:
rotate_array([2,3,4,5,6,3],2)

[6, 3, 2, 3, 4, 5]

#### In case of multidemnsional array

In [6]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

rotated_arr = np.rot90(arr)

print(rotated_arr)


[[3 6 9]
 [2 5 8]
 [1 4 7]]
